### ISSUE TITLE
Hitting error: 'WarmupMultiStepLR' has no attribute 'verbose'

### ISSUE THREAD

**Issue by jbmaxwell** [podgorskiy/ALAE#63]
I'm trying to trying on MNIST and hitting the above error. Here's the backtrace:

```
Traceback (most recent call last):
  File "train_alae.py", line 352, in <module>
    run(train, get_cfg_defaults(), description='StyleGAN', default_config='configs/mnist.yaml',
  File "/home/james/src/spliqsml/ALAE/launcher.py", line 131, in run
    _run(0, world_size, fn, defaults, write_log, no_cuda, args)
  File "/home/james/src/spliqsml/ALAE/launcher.py", line 96, in _run
    fn(**matching_args)
  File "train_alae.py", line 186, in train
    scheduler = ComboMultiStepLR(optimizers=
  File "/home/james/src/spliqsml/ALAE/scheduler.py", line 91, in __init__
    self.schedulers[name] = WarmupMultiStepLR(opt, lr=base_lr, **kwargs)
  File "/home/james/src/spliqsml/ALAE/scheduler.py", line 52, in __init__
    self.step(last_epoch)
  File "/home/james/anaconda3/envs/tf2/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 166, in step
    self.print_lr(self.verbose, i, lr, epoch)
AttributeError: 'WarmupMultiStepLR' object has no attribute 'verbose'
```
Kinda strange, since it seems like that's in your code, but called by torch's lr_scheduler... ??

tensorflow 2.3.1
libcudart.so.10.1

Went through all the setup on new conda env and ran with: `python train_alae.py -c mnist`

Any help appreciated.

**Comment by hri98mahesh** [comment]
I am also facing the same issue. How did you solve this issue ?

**Comment by amruz** [comment]
Refer to issue 66, incase you are still looking for the problem!
