### ISSUE TITLE
ImportError when downloading the data and trying to run the demo 

### ISSUE THREAD

**Issue by Engeloid** [podgorskiy/ALAE#81]
If I run:
`python training_artifacts/download_all.py`
or:
`python interactive_demo.py`

I get:
```
Traceback (most recent call last):
  File "interactive_demo.py", line 21, in <module>
    from dlutils.pytorch import count_parameters
  File "C:\Users\docla\anaconda3\envs\opencv-enc\lib\site-packages\dlutils\__init__.py", line 32, in <module>
    from dlutils.pytorch.jacobian import jacobian
  File "C:\Users\docla\anaconda3\envs\opencv-enc\lib\site-packages\dlutils\pytorch\__init__.py", line 16, in <module>
    from dlutils.pytorch.jacobian import jacobian
  File "C:\Users\docla\anaconda3\envs\opencv-enc\lib\site-packages\dlutils\pytorch\jacobian.py", line 2, in <module>
    from torch.autograd.gradcheck import zero_gradients
ImportError: cannot import name 'zero_gradients'
```

I tried upgrading dlutils but that didn't work.
I was using Python version 3.6.13 using Anaconda on Windows

**Comment by DpangD** [comment]
The latest version of torch has removed the 'zero_gradients' function. Use 1.8.1.

**Comment by Bzz2745** [comment]
Please open the file jacobian.py located at'..\Lib\site-packages\dlutils\pytorch' and change line 21 or 22 of the code zero_gradients(input) to input.zero_grad(). Their functions are the same, but the former has been deprecated in the new version of pytorch. After performing this operation, you can still use ALAE if you change to a new version of pytorch (for example, the pytorch 1.10 version I am using).
